export default {
  LOADING: 'LOADING',
  SET_PLAYER_DATA: 'SET_PLAYER_DATA',
  SET_PLAYER_HEATMAP: 'SET_PLAYER_HEATMAP',
  GoalAttempt: 'GoalAttempt',
  Goal: 'Goal',
  Foul: 'Foul',
  KeyPass: 'KeyPass',
  Pass: 'Pass',
  Intercept: 'Intercept',
  BallPossesion: 'BallPossesion',
  Assist: 'Assist',
  CornerKick: 'CornerKick',
  CrossAttack: 'CrossAttack',
  CounterAttack: 'CounterAttack',
  Dribble: 'Dribble',
}
